# Generated by Django 2.2 on 2020-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
