# Generated by Django 2.2 on 2020-12-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201222_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professor_id',
            new_name='professor',
        ),
    ]
