# Generated by Django 2.2 on 2020-12-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201222_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AddField(
            model_name='course',
            name='professor_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
