# Generated by Django 2.2 on 2020-12-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201222_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='professor_id',
        ),
    ]
