# Generated by Django 2.2 on 2020-12-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
