# Generated by Django 2.2 on 2020-12-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='professor_id',
        ),
    ]
