# Generated by Django 2.2 on 2020-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_remove_professor_professor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
